#!/usr/bin/env bash
COMPILE_LOG=/tmp/ppx_log

make -C .. 2>&1 > $COMPILE_LOG
if [ $? != 0 ]; then
    res=$?
    cat $COMPILE_LOG
    exit $res
fi

ocamlfind c -w -20 -ppx ../_build/src/ppx_getenv.native -c a.ml -dsource
exit $?
