#!/usr/bin/env bash
cat "$1" | sed \
   -e 's/\.$amp$amp/\ \&\&\ /g' \
   -e 's/\.$eq$eq/\ ==\ /g' \
   -e 's/\.$qmark$qmark$qmark/\ \?\?\?\ /g' \
   -e 's/\.$bang$eq/\ !=\ /g' \
   -e 's/\.$bar$bar/\ ||\ /g' \
   -e 's/\.$greater$eq/\ >\= /g' \
   -e 's/\.$less$eq/\ <\=\ /g' \
   -e 's/\.$less/\ <\ /g' \
   -e 's/\.$plus\(1\)/\+1/g' \
   -e 's/\.$plus$eq/\ \+=\ /g' \
   -e 's/fastparsers\.framework\.parseresult\.//g' \
   -e 's/fastparsers\.framework\.implementations\.//g' \
   -e 's/fastparsers\.input\.//g' \
   > "$2"

exit $?
